#!/usr/bin/env node
const path = require('path');

var file = process.argv[2];
if(!file){
  console.log("No input code specified");
} else {
  var fs = require('fs');
  var exec = require('child_process').exec;
  language = require('./language/index');
  session = require('./language/session');
  require('coffee-script/register');
  var Canvas = require('canvas');

  Image = Canvas.Image;
  canvas = new Canvas(1000, 1000);
  ctx = canvas.getContext('2d');

  var code;
  fs.readFile(file,'utf-8', function read(err, data) {
      if (err) {
          throw err;
      }
      code = data;
      processFile();
  });

  function processFile() {
      language.run(code, {ctx: ctx});
      var out = fs.createWriteStream(__dirname +'/'+ path.basename(file,'.draw') +'.png');
      var stream = canvas.pngStream();

      stream.on('data', function(chunk){
        out.write(chunk);
      });

      stream.on('end', function(){
        // console.log("Done");
      });
  }


}